version: '3.8'

services:
  playwright-browser:
    build: .
    container_name: playwright-browser
    ports:
      - "127.0.0.1:6080:6080"  # noVNC web interface - localhost only
      - "127.0.0.1:8931:8931"  # Playwright MCP HTTP/SSE endpoint - localhost only
    environment:
      - DISPLAY=:99
      - RESOLUTION=1920x1080
    volumes:
      - ./data:/data
      - ./mcp-server:/mcp-server:ro
      - ./config:/config:ro
      - /root:/root
    restart: always
    shm_size: '2gb'  # Shared memory for Chrome
    cap_add:
      - SYS_ADMIN  # Required for Chrome sandbox in some cases
    networks:
      - playwright-net
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 512M

volumes:
  browser-data:
    driver: local

networks:
  playwright-net:
    driver: bridge